### PR TITLE
feat(devtools): partial import restrictions

### PR DESCRIPTION
**Pull request by daniellacosse**
enforces our DDD import restrictions with the exception of ui_components, in which there are several rule violations we'll have to address at a later date

### CODE REVIEW

**Comment by daniellacosse** [comment]
> 1. Any code can import from `infrastructure` or third party libraries. You can see infrastructure as standalone app-agnostic libraries, like the third-party libraries. It's nice that we can understand and maintain them in isolation, without needing extra context.
> 2. Perhaps an easier way to think about the rules is this: app > model | ui components > infrastructure > third party. Where things on the left can depend on the right, but model and ui can't depend on each other (it's a layered architecture!).
> 3. We treat `outline-gcp-create-server-app.ts` as a nested app, so it can depend on the model. It should probably move out of `ui_components`. Perhaps straight into `web_app/`.

okay, here's the current list of errors now - are these accurate?

```
outline-server/src/server_manager/web_app/ui_components/outline-per-key-data-limit-dialog.ts
  35:8  error  Unexpected path "../data_formatting" imported in restricted zone  import/no-restricted-paths

outline-server/src/server_manager/web_app/ui_components/outline-region-picker-step.ts
  23:35  error  Unexpected path "../../model/location" imported in restricted zone    import/no-restricted-paths
  24:45  error  Unexpected path "../location_formatting" imported in restricted zone  import/no-restricted-paths

outline-server/src/server_manager/web_app/ui_components/outline-server-settings.ts
  29:32  error  Unexpected path "../data_formatting" imported in restricted zone      import/no-restricted-paths
  31:28  error  Unexpected path "../location_formatting" imported in restricted zone  import/no-restricted-paths

outline-server/src/server_manager/web_app/ui_components/outline-server-view.ts
  39:29  error  Unexpected path "../data_formatting" imported in restricted zone      import/no-restricted-paths
  40:28  error  Unexpected path "../location_formatting" imported in restricted zone  import/no-restricted-paths
  45:34  error  Unexpected path "../../model/location" imported in restricted zone    import/no-restricted-paths
  46:32  error  Unexpected path "../../model/server" imported in restricted zone      import/no-restricted-paths

outline-server/src/shadowbox/infrastructure/filesystem_text_file.ts
  16:24  error  Unexpected path "../model/text_file" imported in restricted zone  import/no-restricted-paths
```

**Comment by fortuna** [comment]
Move shadowbox/model/text_file.ts  to shadowbox/infrastructure. That should fix it.

**Comment by fortuna** [comment]
BTW, it seems that server_manager/web_app/data_formatting.ts could also move to infrastructure. It has no imports and is quite application agnostic.

**Comment by daniellacosse** [comment]
> data_formatting

it seems there's something to do with it requiring a browser context, if you look at the karma config? https://github.com/Jigsaw-Code/outline-server/blob/8836bdea1486f703488c9feaf1f78020e3f04295/src/server_manager/web_app/karma.conf.js#L25-L27

**Comment by fortuna** [comment]
I wonder how we can indicate that certain code only runs in some environments (electron main, electron renderer, node, browser, anywhere, ...)

**Comment by daniellacosse** [comment]
> I wonder how we can indicate that certain code only runs in some environments (electron main, electron renderer, node, browser, anywhere, ...)

I've been thinking about this and presently i think things _can_ be coerced into one of two categories - platform specific and platform agnostic

in a NPM workspace, we can scope type definition to the sub-packages that import them

for platform agnostic code, we can co-locate those packages in a separate group and ensure the tsconfig for those modules have no `types` (https://www.typescriptlang.org/tsconfig#types) - so if we were to, for instance, try to use node things there TS should fail to build.

for platform specific code, it seems that most platform support some kind of indicator in the `package.json`? so if we split those packages into their own group, each package can at minimum imply what it is based on its package.json configuration. we can also enforce this further with typescript

**Pull request merged**
