### PR TITLE
Revert "refactor(manager): replace share s3 flow with self-contained instructions"

### PR DESCRIPTION
**Pull request by daniellacosse**
Reverts Jigsaw-Code/outline-server#1133

### CODE REVIEW

**Review by jyyi1 — APPROVED** [review]
LGTM

**Comment by kevindamm-jigsaw** [comment]
LGTM does this need translations to be reverted too?

**Comment by daniellacosse** [comment]
> LGTM does this need translations to be reverted too?

Ah, yes - It should be a recent PR. Double check that that's a clean revert, too.

**Comment by kevindamm-jigsaw** [comment]
yeah, I think it was #1158
https://github.com/Jigsaw-Code/outline-server/pull/1158

there was another translation change for the price update but I think that doesn't need to be reverted (and was before the above PR so shouldn't conflict, either)

**Comment by daniellacosse** [comment]
> yeah, I think it was #1158
> 
> there was another translation change for the price update but I think that doesn't need to be reverted (and was before the above PR so shouldn't conflict, either)

Awesome, make it so

**Review by kevindamm-jigsaw — APPROVED** [review]

**Pull request merged**
