### PR TITLE
feat(server): add vulnerability analysis by CodeQL

### PR DESCRIPTION
**Pull request by murka**

### CODE REVIEW

**Comment by murka** [comment]
I did it

**Comment by murka** [comment]
So, codeql scanning result failing, because we are not validation certs, but you can ignore that on "Security" tab.

**Comment by murka** [comment]
@daniellacosse, PR ready to merge in master branch!

**Comment by fortuna** [comment]
@murka is it possible to disable the two tests that are failing with an exception?

The certificate validation is disabled because we explicitly validate it with the pin. There's nothing to fix there.
The cloud request is not rate-limited, but we're not fixing it at this moment. Perhaps we can add a TODO

**Comment by murka** [comment]
@fortuna, FYI: https://github.com/Jigsaw-Code/outline-server/pull/1271/commits/0e150b60d307a6760c8c3e02412d0cae06092def

**Comment by murka** [comment]
I fixed [4058989735](https://github.com/Jigsaw-Code/outline-server/actions/runs/4058989735) on [26c77ee](https://github.com/Jigsaw-Code/outline-server/pull/1271/commits/26c77ee12a8d19c9476ddd5fe4c3eb99f3877921)

**Comment by murka** [comment]
@daniellacosse @fortuna, do you have any feedbacks about this PR?

**Comment by fortuna** [comment]
Thanks @murka for the contribution!

**Pull request merged**
