### PR TITLE
Update the watchtower image name

### PR DESCRIPTION
**Pull request by Rowno**
It looks like the watchtower repo was renamed to `containrrr/watchtower` sometime ago and the old `v2tec/watchtower` image hasn't been updated for over a year.

### CODE REVIEW

**Comment by HenryQW** [comment]
Please rebase and merge this PR asap, thank you. @JonathanDCohen @alalamav

**Comment by Rowno** [comment]
Done

**Comment by HenryQW** [comment]
@fortuna v2tec was renamed to containrrr. v2tec/watchtower image hasn't been updated for 2 years now.

**Comment by Rowno** [comment]
I have no idea how to test changes to `outline-server`. But after setting up a fresh Outline droplet I used docker to get the flags that the `v2tec/watchtower` container was started with, brought down `v2tec/watchtower` and then started `containrrr/watchtower` with the same flags and it seems to work fine.

**Pull request merged**
