### PR TITLE
Correct the link of official website

### PR DESCRIPTION
**Pull request by zhiwei-xu**

### CODE REVIEW

**Comment by zhiwei-xu** [comment]
CLA signed.

**Comment by trevj** [comment]
@zhiwei-xu Thanks for the fix!

**Comment by trevj** [comment]
This is a followup to:
https://github.com/Jigsaw-Code/outline-server/pull/76

**Comment by trevj** [comment]
Weird, Travis never reported on this PR. Merging anyway since it clearly can't break the build.

**Pull request merged**
