### PR TITLE
fix(manager): specify a higher per_page for DigitalOcean API call

### LINKED ISSUE #999: [bug] outline manager list only 20 droplet from digital ocean
[bug] outline manager list only 20 droplet from digital ocean if have more than 20 it show only 20

### PR DESCRIPTION
**Pull request by cgarvey**
Default (if not specified) is 20. Increase to 100 (tested).

Fixes #999.

### CODE REVIEW

**Review by fortuna — CHANGES_REQUESTED** [review]
Thanks for the fix!

**Comment by cgarvey** [comment]
> Thanks for the fix!

Review recommendations noted and actions. Let me know if that's enough for an iteration (until pagination proper is implemented, as you say). Thanks

**Review by fortuna — APPROVED** [review]

**Comment by fortuna** [comment]
For some reason the status seems to be stuck...

**Comment by fortuna** [comment]
@cgarvey you may need to pull master to trigger the tests again.

**Comment by cathal-lu** [comment]
> @cgarvey you may need to pull master to trigger the tests again.

Done, sorry I missed the comment. Latest master merged in now. Let me know if there's anything else I can do to help

**Comment by cgarvey** [comment]
> @cgarvey you may need to pull master to trigger the tests again.

Done, sorry I missed the comment. Latest master merged in now. Let me know if there's anything else I can do to help

**Pull request merged**
